readonly SCAFFOLD_CONFIG_DIRECTORY="config"
readonly SCAFFOLD_CONFIG_PATH="${SCAFFOLD_PATH}/${SCAFFOLD_CONFIG_DIRECTORY}"

readonly SCAFFOLD_CONFIG_FILE_SAMPLE_CONFIG=".scaffold.example"
readonly SCAFFOLD_CONFIG_PATH_SAMPLE_CONFIG="${SCAFFOLD_PATH}/${SCAFFOLD_CONFIG_FILE_SAMPLE_CONFIG}"

readonly SCAFFOLD_CONFIG_DIRECTORY_COMMANDS="commands"
readonly SCAFFOLD_CONFIG_PATH_COMMANDS="${SCAFFOLD_PATH}/${SCAFFOLD_CONFIG_DIRECTORY_COMMANDS}"
readonly SCAFFOLD_CONFIG_COMMAND_DEFAULT="help"

readonly SCAFFOLD_CONFIG_FILE_PACKAGE_EXTENSIONS="package_extensions.config"
readonly SCAFFOLD_CONFIG_PATH_PACKAGE_EXTENSIONS="${SCAFFOLD_CONFIG_PATH}/${SCAFFOLD_CONFIG_FILE_PACKAGE_EXTENSIONS}"

readonly SCAFFOLD_CONFIG_FILE_PACKABLE_DIRECTORIES="packable_directories.config"
readonly SCAFFOLD_CONFIG_PATH_PACKABLE_DIRECTORIES="${SCAFFOLD_CONFIG_PATH}/${SCAFFOLD_CONFIG_FILE_PACKABLE_DIRECTORIES}"

readonly SCAFFOLD_CONFIG_FILE_UNPACKABLE_DIRECTORIES="unpackable_directories.config"
readonly SCAFFOLD_CONFIG_PATH_UNPACKABLE_DIRECTORIES="${SCAFFOLD_CONFIG_PATH}/${SCAFFOLD_CONFIG_FILE_UNPACKABLE_DIRECTORIES}"

readonly SCAFFOLD_MOD_DIRECTORY_CONFIG=".scaffold"
readonly SCAFFOLD_MOD_PATH_CONFIG="${SCAFFOLD_MOD_PATH}/${SCAFFOLD_MOD_DIRECTORY_CONFIG}"

readonly SCAFFOLD_MOD_FILE_CONFIG="config.sh"
readonly SCAFFOLD_MOD_RELATIVE_PATH_CONFIG_FILE="${SCAFFOLD_MOD_DIRECTORY_CONFIG}/${SCAFFOLD_MOD_FILE_CONFIG}"
readonly SCAFFOLD_MOD_PATH_CONFIG_FILE="${SCAFFOLD_MOD_PATH}/${SCAFFOLD_MOD_RELATIVE_PATH_CONFIG_FILE}"

readonly SCAFFOLD_MOD_FILE_PACKAGE_EXCLUSIONS="exclusion_pattern.txt"
readonly SCAFFOLD_MOD_RELATIVE_PATH_PACKAGE_EXCLUSIONS="${SCAFFOLD_MOD_DIRECTORY_CONFIG}/${SCAFFOLD_MOD_FILE_PACKAGE_EXCLUSIONS}"
readonly SCAFFOLD_MOD_PATH_PACKAGE_EXCLUSIONS="${SCAFFOLD_MOD_PATH}/${SCAFFOLD_MOD_RELATIVE_PATH_PACKAGE_EXCLUSIONS}"

readonly SCAFFOLD_MOD_DIRECTORY_DATA="Data"
readonly SCAFFOLD_MOD_PATH_DATA="${SCAFFOLD_MOD_PATH}/${SCAFFOLD_MOD_DIRECTORY_DATA}"

readonly SCAFFOLD_MOD_FILE_ACHLIST="package.achlist"
readonly SCAFFOLD_MOD_PATH_ACHLIST="${SCAFFOD_MOD_PATH}/${SCAFFOLD_MOD_FILE_ACHLIST}"

readonly SCAFFOLD_MOD_EXTENSION_ESM="esm"
readonly SCAFFOLD_MOD_EXTENSION_ESP="esp"
readonly SCAFFOLD_MOD_EXTENSIONS_PLUGIN=( $(echo "${SCAFFOLD_MOD_EXTENSION_ESM,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESP,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESM^^}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESP^^}") )
