readonly SCAFFOLD_NAME_DIRECTORY_CONFIG=".scaffold"
readonly SCAFFOLD_NAME_DIRECTORY_COMMANDS="commands"
readonly SCAFFOLD_NAME_DIRECTORY_GLOBAL="global"
readonly SCAFFOLD_NAME_DIRECTORY_GAMES="games"
readonly SCAFFOLD_NAME_DIRECTORY_TEMP="temp"
readonly SCAFFOLD_NAME_DIRECTORY_DATA="Data"

readonly SCAFFOLD_NAME_FILE_CONFIG="config.sh"
readonly SCAFFOLD_NAME_FILE_EXCLUSIONPATTERN="exclusion-pattern.txt"
readonly SCAFFOLD_NAME_FILE_DEPENDENCIES="dependencies.list"
readonly SCAFFOLD_NAME_FILE_ARCHIVEEXTENSIONS="archive-extensions.list"
readonly SCAFFOLD_NAME_FILE_PLUGINEXTENSIONS="plugin-extensions.list"
readonly SCAFFOLD_NAME_FILE_SYMLINKLOCATIONS="symlink-locations.list"
readonly SCAFFOLD_NAME_FILE_ACHLIST="package.achlist"

readonly SCAFFOLD_DIRECTORY_SCRIPTS="Scripts"
readonly SCAFFOLD_DIRECTORY_SOURCE="Source"

readonly SCAFFOLD_DIRECTORY_MESHES="Meshes"
readonly SCAFFOLD_DIRECTORY_PRECOMBINED="PreCombined"

readonly SCAFFOLD_MOD_EXTENSION_ESM="esm"
readonly SCAFFOLD_MOD_EXTENSION_ESP="esp"
readonly SCAFFOLD_MOD_EXTENSION_ESL="esl"
readonly SCAFFOLD_MOD_EXTENSIONS_PLUGIN=( $(echo "${SCAFFOLD_MOD_EXTENSION_ESM,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESM^^}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESL,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESL^^}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESP,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESP^^}") )

readonly SCAFFOLD_MOD_EXTENSIONS_PACKAGE=( $(echo "${SCAFFOLD_MOD_EXTENSION_PACKAGE,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_PACKAGE^^}") )

readonly RELEASE_FLAG="--release"
if [[ $2 == $RELEASE_FLAG ]]
then
	readonly RELEASING=1
else
	readonly RELEASING=0
fi
