readonly SCAFFOLD_DIRECTORY_SCRIPTS="Scripts"
readonly SCAFFOLD_DIRECTORY_SOURCE="Source"

readonly SCAFFOLD_CONFIG_DIRECTORY="config"
readonly SCAFFOLD_CONFIG_PATH="$SCAFFOLD_PATH/$SCAFFOLD_CONFIG_DIRECTORY"

readonly SCAFFOLD_CONFIG_FILE_SAMPLE_CONFIG=".scaffold.sample"
readonly SCAFFOLD_CONFIG_PATH_SAMPLE_CONFIG="$SCAFFOLD_PATH/$SCAFFOLD_CONFIG_FILE_SAMPLE_CONFIG"

readonly SCAFFOLD_CONFIG_DIRECTORY_COMMANDS="commands"
readonly SCAFFOLD_CONFIG_PATH_COMMANDS="$SCAFFOLD_PATH/$SCAFFOLD_CONFIG_DIRECTORY_COMMANDS"
readonly SCAFFOLD_CONFIG_COMMAND_DEFAULT="help"

readonly SCAFFOLD_CONFIG_FILE_PACKAGE_EXTENSIONS="package_extensions.config"
readonly SCAFFOLD_CONFIG_PATH_PACKAGE_EXTENSIONS="$SCAFFOLD_CONFIG_PATH/$SCAFFOLD_CONFIG_FILE_PACKAGE_EXTENSIONS"

readonly SCAFFOLD_CONFIG_FILE_SYMLINK_LOCATIONS="symlink_locations.config"
readonly SCAFFOLD_CONFIG_PATH_SYMLINK_LOCATIONS="$SCAFFOLD_CONFIG_PATH/$SCAFFOLD_CONFIG_FILE_SYMLINK_LOCATIONS"

readonly SCAFFOLD_MOD_DIRECTORY_CONFIG=".scaffold"
readonly SCAFFOLD_MOD_PATH_CONFIG="$SCAFFOLD_MOD_PATH/$SCAFFOLD_MOD_DIRECTORY_CONFIG"

readonly SCAFFOLD_MOD_FILE_CONFIG="config.sh"
readonly SCAFFOLD_MOD_RELATIVE_PATH_CONFIG_FILE="$SCAFFOLD_MOD_DIRECTORY_CONFIG/$SCAFFOLD_MOD_FILE_CONFIG"
readonly SCAFFOLD_MOD_PATH_CONFIG_FILE="$SCAFFOLD_MOD_PATH/$SCAFFOLD_MOD_RELATIVE_PATH_CONFIG_FILE"

readonly SCAFFOLD_MOD_FILE_EXCLUSION="exclusionpattern.txt"
readonly SCAFFOLD_MOD_RELATIVE_PATH_EXCLUSION_FILE="$SCAFFOLD_MOD_DIRECTORY_CONFIG/$SCAFFOLD_MOD_FILE_EXCLUSION"
readonly SCAFFOLD_MOD_PATH_EXCLUSION_FILE="$SCAFFOLD_MOD_PATH/$SCAFFOLD_MOD_RELATIVE_PATH_EXCLUSION_FILE"

readonly SCAFFOLD_MOD_DIRECTORY_DATA="Data"
readonly SCAFFOLD_MOD_PATH_DATA="$SCAFFOLD_MOD_PATH/$SCAFFOLD_MOD_DIRECTORY_DATA"

readonly SCAFFOLD_MOD_FILE_ACHLIST="package.achlist"
readonly SCAFFOLD_MOD_PATH_ACHLIST="$SCAFFOLD_MOD_PATH/$SCAFFOLD_MOD_FILE_ACHLIST"

readonly SCAFFOLD_MOD_EXTENSION_ESM="esm"
readonly SCAFFOLD_MOD_EXTENSION_ESP="esp"
readonly SCAFFOLD_MOD_EXTENSIONS_PLUGIN=( $(echo "${SCAFFOLD_MOD_EXTENSION_ESM,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESM^^}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESP,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_ESP^^}") )

readonly SCAFFOLD_MOD_EXTENSION_PACKAGE="ba2"
readonly SCAFFOLD_MOD_EXTENSIONS_PACKAGE=( $(echo "${SCAFFOLD_MOD_EXTENSION_PACKAGE,,}") $(echo "${SCAFFOLD_MOD_EXTENSION_PACKAGE^^}") )

readonly RELEASE_FLAG="--release"
if [[ $2 == $RELEASE_FLAG ]]
then
	readonly RELEASING=1
else
	readonly RELEASING=0
fi
