source "$SCAFFOLD_CONFIG_PATH_INCLUDE_MOD_CONFIGURATION"

if [[ -z $SCAFFOLD_MOD_DELIVERABLES_PATH ]]
then
	echo "Mod deliverable path is not configured, cannot build deliverable" >&2
	exit 1
fi

readonly SCAFFOLD_DELIVERABLE_PATH_TEMP="$SCAFFOLD_MOD_DELIVERABLES_PATH/$SCAFFOLD_DIRECTORY_TEMP"
readonly SCAFFOLD_DELIVERABLE_PATH_TEMP_DATA="$SCAFFOLD_DELIVERABLE_PATH_TEMP/$SCAFFOLD_MOD_DIRECTORY_DATA"

readonly LOOSE_FILES="LooseFiles"
readonly DELIVERABLE_PATH_SEPARATOR="_"
readonly DELIVERABLE_PATH_BASE="$SCAFFOLD_MOD_DELIVERABLES_PATH/$SCAFFOLD_MOD_NAME"
