readonly SCAFFOLD_PATH_DELIVERABLE_MOD="$SCAFFOLD_GAME_DELIVERABLE_PATH/$SCAFFOLD_MOD"

readonly SCAFFOLD_PATH_GAME_DELIVERABLE_TEMP="$SCAFFOLD_GAME_DELIVERABLE_PATH/$SCAFFOLD_NAME_DIRECTORY_TEMP"
readonly SCAFFOLD_PATH_GAME_DELIVERABLE_TEMP_DATA="$SCAFFOLD_PATH_GAME_DELIVERABLE_TEMP/$SCAFFOLD_NAME_DIRECTORY_DATA"

if [[ "$LOOSE" ]]
then
	readonly SCAFFOLD_DELIVERABLE_PATH="$SCAFFOLD_PATH_DELIVERABLE_MOD$SCAFFOLD_DELIVERABLE_SEPARATOR$SCAFFOLD_DELIVERABLE_LOOSEFILES"
else
	readonly SCAFFOLD_DELIVERABLE_PATH="$SCAFFOLD_PATH_DELIVERABLE_MOD"
fi
